### ISSUE TITLE
SaveFileDialog creates and deletes entered file name

### ISSUE THREAD

**Issue by DrCQ** [FantasticFiasco/mvvm-dialogs#106]
I'm using the `OpenFileDialog` and `SaveFileDialog` in my WPF application. Now I found a strange behavior of the `SaveFileDialog`. After entering a new file name the Dialog is internally creating and than deleting the selected file. I set the `CheckFileExist` property to false but don't found a way how to suppress this behavior.  
I'm using the `FileWatcher` class to monitor changes to the selected folder and this create/delete action disturb the internal workflow of my application. I have some asynchronous task triggered by the `FileWatcher`.
It is a way to suppress or remove this create/delete process?

**Comment by FantasticFiasco** [comment]
Is it easy to reproduce the issue? Would you be able to create and share a small sample application demonstrating the issue?

**Comment by DrCQ** [comment]
Hi Mattias, I started to build a small test application using MvvmLight and MvvmDialogs but encountered problem "DialogServiceViews.IsRegistered doesn't exists in XML namespace" etc.
So I stop here. For my original problem I found a workaround while suppressing the file create/remove notification as long as the FileSaveDialog is used.
Thanks for your fast response!

**Comment by FantasticFiasco** [comment]
Ok, but please get back to me if you find other issues along your way. I wish you all the best on your future endeavours.
