### ISSUE TITLE
ShowDialog with Callback

### ISSUE THREAD

**Issue by mysteryx93** [FantasticFiasco/mvvm-dialogs#109]
I was going through Prism documentation and reading about Interaction Service to deal with windows.

[The documentation states:](https://prismlibrary.com/docs/wpf/legacy/Advanced-MVVM.html#using-an-interaction-service)

> [...] can be implemented in a synchronous way, using a blocking method call. However, one of the disadvantages of this approach is that it forces a synchronous programming model. An alternative asynchronous implementation allows for the view model to provide a callback to execute on completion of the interaction. The asynchronous approach provides greater flexibility when implementing the interaction service by allowing modal and non-modal interactions to be implemented.

Do you think it would be good to implement this in Mvvm-Dialogs?

As it stands, calling ShowDialog locks the calling ViewModel in a synchronous way.

**Comment by FantasticFiasco** [comment]
Hi @mysteryx93 and thank you for your comment.

I definitely think some developers, perhaps like yourself, would rather write their code using callbacks. Perhaps you started out in Node.js where everything was callbacks, and you've grown accustomed to that pattern? But then again, later versions of JavaScript adds support for `Promise` and `async`/`await`, and one of the reasons for adding those was [callback hell](https://blog.hellojs.org/asynchronous-javascript-from-callback-hell-to-async-and-await-9b9ceb63c8e8). Don't get me wrong. I don't bash on the asynchronous model, I'm merely stating that the asynchronous model isn't **always** better, in response to the quote from the Prism documentation.

Back to what we know. I would argue that most developers building UI for Windows would do so in WPF, or WinForms if you are unlucky. And these developers are all accustomed to the synchronous model of opening modal dialogs, would you agree? So by supporting the same model in this library, I'm providing what would be expected, and that's a good thing. It means that I don't run into the risk of alienating potential consumers of this library.

Let me end by asking you a question. What benefits, other than personal taste, would you foresee if this library also supported a asynchronous API?

**Comment by mysteryx93** [comment]
Thinking of it. Was this doc written before async / await was added to the framework? This could definitely be done with ShowModalAsync.

It's not really a problem for myself, but I'm thinking. The ViewModel shouldn't care about the UI, whether it is WPF, WinForms or anything else. Modal windows show in a synchronous way, and that's not the ViewModel's concern. What if the ViewModel is performing an operation like a download, then showing a message in the middle? That would lock the whole ViewModel, and it doesn't have to.

I'm not sure in what use-cases this would actually make a difference, but adding an Async version of modal dialogs may not be a bad idea.

For one, it would make for cleaner code by not locking the code in a synchronous way. For two, it allows you to achieve other work while the user is responding.

**Comment by FantasticFiasco** [comment]
> The ViewModel shouldn't care about the UI, whether it is WPF, WinForms or anything else.

This is wishful thinking. This most often doesn't make sense. Not using the tools the specific framework you've chosen hands you will cost you in the end. I've heard this statement from applications that are migrating from WinForms to WPF and currently are in a state where they have the two frameworks mixed, and it isn't any fun.

You should start with asking yourself why you make that statement. Accept that there is a coupling between view and view model, and start thinking about what you will gain from actually separating them. When you know what you gain, you'll know which guidelines to follow and which to ignore.

> For one, it would make for cleaner code by not locking the code in a synchronous way. For two, it allows you to achieve other work while the user is responding.

I've heard this statement before, that just because you open a new dialog you don't get any new updates in the UI while the modal dialog is shown. This is simply not true. I've created a small sample, you can find it [here](https://github.com/FantasticFiasco/modal-dialog-does-not-block).

The sample application will show the current time and a button beneath it. When you press the button a new modal dialog is opened, and the synchronous dialog service is waiting for the dialog to return its value. But the current time in the application is still being updated, proving the claim that opening a modal dialog doesn't block the UI thread.

**Comment by mysteryx93** [comment]
Here's a use-case where this would be useful.

1. You have a complex window to enter settings
2. You click Run to perform a long operation in the ViewModel
3. You open a Dialog window to show the progress and lock the main window until it's done
4. The ViewModel updates the Dialog's progress along the way

something like 

    private void OpenModalDialog(object parameter)
    {
        var vm = new ModalDialogViewModel();
        var dialogTask = _dialogService.ShowDialogAsync(this, vm);
        for (int i = 0; i < 100; i++)
        {
            vm.Progress = i;
        }
        vm.Close();
        var result = await dialogTask;
    }

That being said, ShowDialogAsync could probably be added to the interface via an extension method. 

Other than special cases like this, I don't know whether it would have other effects on the code, maintenance or extensibility.

**Comment by mysteryx93** [comment]
As I started playing with it, I found another aspect to consider: ShowDialog must be called from the UI thread; whereas ShowDialogAsync would invoke the method on the UI thread.

An Async method would allow calling it from non-UI threads.

I wrote extension methods liike this

    public static class DialogExtensions
    {
        public static async Task<SelectPresetViewModel?> ShowSelectPresetViewAsync(this IDialogService dialog, INotifyPropertyChanged ownerViewModel, bool modeSave)
        {
            var selectPreset = ViewModelLocator.SelectPreset.Load(modeSave);
            var result = await ShowDialogAsync(dialog, ownerViewModel, selectPreset).ConfigureAwait(true);
            return result == true ? selectPreset : null;
        }

        public static async Task<bool?> ShowDialogAsync(this IDialogService dialog, INotifyPropertyChanged ownerViewModel, IModalDialogViewModel viewModel)
        {
            return await Dispatcher.CurrentDispatcher.InvokeAsync(() => dialog.ShowDialog(ownerViewModel, viewModel));
        }

        //private static bool IsUiThread() => Thread.CurrentThread == System.Windows.Threading.Dispatcher.CurrentDispatcher.Thread;
    }

**Comment by FantasticFiasco** [comment]
If you are content with extending the interface like you've shown, that is probably best for us both. I'm hesitant to update the API for this, and if you can get it to work without having to wait for an implementation in this library, we can probably close this issue and consider the outcome successful?
