### ISSUE TITLE
Crash on loading ModelView.

### ISSUE THREAD

**Issue by JohnyMac** [FantasticFiasco/mvvm-dialogs#13]
I am trying to use this library with MvvmLight but I get this exception: 
http://prntscr.com/ciegxr

Whenever I remove the IDialogService parameter from the ModelView constructor, it works properly.

How to fix this ? Thanks in advanced.

**Comment by FantasticFiasco** [comment]
Have you registered `IDialogService` with the IoC container in MvvmLight? Many of my samples in the source use MvvmLight, and their App.xaml.cs looks loke this:

```
public partial class App
{
    protected override void OnStartup(StartupEventArgs e)
    {
        SimpleIoc.Default.Register<IDialogService>(() => new DialogService());
    }
}
```

**Comment by JohnyMac** [comment]
Nope, I didn't, That's most likely the issue then.

Thanks.
