### ISSUE TITLE
Question: Why register the dialog?

### ISSUE THREAD

**Issue by virzak** [FantasticFiasco/mvvm-dialogs#130]
Just wondering what's the idea behind registering the dialog. Seems like it is working just fine without it. 

https://github.com/FantasticFiasco/mvvm-dialogs/blob/aadef2e6a757d4ccfcb3f3862da5660a4e43a4ad/samples/net-core/Demo.ModalCustomDialog/ViewModelLocator.cs#L14

**Comment by FantasticFiasco** [comment]
You are correct, this looks to be a bug. We only need to register that view models that open dialogs, and this one doesn't.

Are you participating in the currently ongoing [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? In that case you are free to open a PR fixing the issue, and I'll make sure it counts towards your goal.

If you aren't participating I'll fix the issue myself.

**Comment by virzak** [comment]
Will give it to a participating friend :) Thanks.

**Comment by FantasticFiasco** [comment]
Thinking about it again, the IoC container has nothing to do with MVVMDialogs, it has to do with MVVM Light. If the behavior of the sample is identical given we don't register the view model, the registering can be removed. But let me emphasise again, it has nothing to do with MVVMDialogs.

**Comment by virzak** [comment]
For sure. The reason I'm bringing this up is because the project I've been working on with a team, which has about 10 dialogs has resulted in 10 extra lines of code in the project.

Then someone used this:
```csharp
var dialogVM = SimpleIoc.Default.GetInstance<AddTextCustomDialogViewModel>();
```
which limited passing constructor arguments to the view model.

So while it is definitely not a bug, it may lead to some confusion / improper use. Perhaps there could be a separate example where MainViewModel is being injected with a DialogViewModel, which in turn is being injected with some service.

**Comment by FantasticFiasco** [comment]
The changes have now made it to `master`. Thanks for bringing the issue to my attention.
