### ISSUE TITLE
datacontext

### ISSUE THREAD

**Issue by MannusEtten** [FantasticFiasco/mvvm-dialogs#152]
hello!

i am using your library and it is nice. But now I ran into an issue.
I do have an usercontrol-view but it is really an usercontrol so the datacontext is not on the whole usercontrol but on a grid with the key "LayoutRoot".

So when i try to use the dialogservice in the viewmodel the following message occurs:"View model of type 'theRightDirection.PortalOptimizer.Desktop.Controls.Login.ViewModel.PortalLoginViewModel' is not present as data context on any registered view. Please register the view by setting DialogServiceViews.IsRegistered="True" in your XAML."

My view:

<UserControl x:Class="theRightDirection.PortalGenius.Desktop.Controls.Login.PortalLogin"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:xaml="clr-namespace:theRightDirection.WPF.Xaml;assembly=theRightDirection.WPF.Xaml"
             xmlns:converters="clr-namespace:theRightDirection.PortalGenius.Desktop.Controls.Converters;assembly=theRightDirection.PortalGenius.Desktop.Controls"
             xmlns:controls="clr-namespace:theRightDirection.PortalGenius.Desktop.Controls;assembly=theRightDirection.PortalGenius.Desktop.Controls"
             xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
             xmlns:converters1="clr-namespace:theRightDirection.PortalOptimizer.Desktop.Controls.Login.Converters"
             xmlns:converters2="clr-namespace:theRightDirection.WPF.Xaml.Converters;assembly=theRightDirection.WPF.Xaml"
             xmlns:md="https://github.com/fantasticfiasco/mvvm-dialogs"
             md:DialogServiceViews.IsRegistered="True"
             mc:Ignorable="d"
             d:DesignHeight="450" d:DesignWidth="800">
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/theRightDirection.PortalGenius.Desktop.Controls;component/Styles/Brush.xaml" />
                <ResourceDictionary Source="/theRightDirection.PortalGenius.Desktop.Controls;component/Styles/Image.xaml" />
                <ResourceDictionary Source="/theRightDirection.PortalGenius.Desktop.Controls;component/IconButton.xaml" />
                <ResourceDictionary Source="/theRightDirection.PortalGenius.Desktop.Controls;component/Styles/TextBox.xaml" />
                <ResourceDictionary Source="/theRightDirection.PortalGenius.Desktop.Controls;component/Styles/TextBlock.xaml" />
                <ResourceDictionary Source="/theRightDirection.PortalGenius.Desktop.Controls;component/Text.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <Style x:Key="button1" TargetType="Button" BasedOn="{StaticResource IconButtonMaterial}">
                <Setter Property="VerticalAlignment" Value="Bottom" />
                <Setter Property="controls:IconButton.MaterialIcon" Value="LoginVariant" />
            </Style>
            <Style x:Key="button2" TargetType="Button" BasedOn="{StaticResource IconFileIcons}">
                <Setter Property="VerticalAlignment" Value="Bottom" />
                <Setter Property="controls:IconButton.FileIconsIcon" Value="TestDir" />
            </Style>
            <Style TargetType="TextBlock" x:Key="grid">
                <Setter Property="Foreground" Value="Black" />
                <Setter Property="VerticalAlignment" Value="Center" />
                <Setter Property="Margin" Value="0 0 0 10" />
            </Style>
            <Style TargetType="TextBlock" x:Key="grid2">
                <Setter Property="Foreground" Value="{StaticResource tRDGrayBrush}" />
                <Setter Property="VerticalAlignment" Value="Center" />
                <Setter Property="Margin" Value="0 0 0 10" />
            </Style>
            <Style TargetType="TextBox" BasedOn="{StaticResource PGTextBoxStyle}">
                <Setter Property="Foreground" Value="{StaticResource tRDGrayBrush}" />
                <Setter Property="VerticalAlignment" Value="Center" />
                <Setter Property="Margin" Value="0 0 0 10" />
                <Setter Property="Height" Value="25" />
            </Style>
            <Style TargetType="PasswordBox">
                <Setter Property="Margin" Value="0 0 0 10" />
                <Setter Property="Height" Value="25" />
            </Style>
            <SolidColorBrush x:Key="LoginNotOkColor" Color="Red" />
            <converters1:LoginStatusToIconConverter x:Key="LoginStatusToIconConverter" />
            <converters1:LoginStatusToColorConverter x:Key="LoginStatusToColorConverter" LoginOkColor="{StaticResource tRDGreenBrush}" LoginNotOkColor="{StaticResource LoginNotOkColor}" />
            <BooleanToVisibilityConverter x:Key="BooleanToVisibilityConverter" />
            <converters2:InverseBooleanToVisibilityConverter x:Key="InverseBooleanConverter" />
            <converters:PortalTypeToVisibilityConverter x:Key="PortalTypeToVisibilityConverter" />
            <converters:VisibilityByPortalInformationConverter x:Key="enterpriseVisibilityConverter" RequestArcGisPortalType="ArcGISEnterprise" />
            <converters:VisibilityByPortalInformationConverter x:Key="onlineVisibilityConverter" RequestArcGisPortalType="ArcGISOnline" />
            <converters:VisibilityByPortalInformationConverter x:Key="portalTypeKnownVisibilityConverter" />
            <converters2:StringIsNotNullOrEmptyToVisibilityConverter x:Key="StringVisibilityConverter" />
        </ResourceDictionary>
    </UserControl.Resources>
    <Grid x:Name="LayoutRoot" Width="1000">

        public PortalLogin()
        {
            InitializeComponent();
            LayoutRoot.DataContext = new PortalLoginViewModel();
        }

I hope you make an adjustment for this.

**Comment by FantasticFiasco** [comment]
Hi @MannusEtten!

Would you be able to create a small GitHub repo with a basic application showing your issue? I think it would eliminate any misunderstandings from my point. Thanks!

**Comment by MannusEtten** [comment]
yeah i have to see , i think i worked around it

**Comment by FantasticFiasco** [comment]
I'll close the issue for now, and if you still have problems further on, I'll reopen it again.
