### ISSUE TITLE
'Sequence contains more than one matching element' when using IServiceProvider in App setting

### ISSUE THREAD

**Issue by meilleur102** [FantasticFiasco/mvvm-dialogs#157]
Hi! 
Ive use the DialogService on a lot of project recently and everything work perfectly. 
In my Mvvm structure Ive add some IserviceProvider in the App.xaml.cs and now when I try to open the FileBrowser I have this error. 
Sequence contains more than one matching element. 

I try to put the new DialogService() in all the place but nothing works. 
I try to put the DialogService in the IServiceCollection but nothing unfortunatly. 
This is my App.xaml.cs. 

```
    public partial class App : Application
        {
            protected override void OnStartup(StartupEventArgs e)
            {
                IServiceProvider serviceProvider = CreateServiceProvider();

            Window window = serviceProvider.GetRequiredService<MainWindow>();
            window.Show();

            base.OnStartup(e);
        }
        private IServiceProvider CreateServiceProvider()
        {

            IServiceCollection services = new ServiceCollection();

            services.AddSingleton<IAuthenticationService, AuthenticationService>();


            services.AddScoped<INavigator, Navigator>();
            services.AddScoped<IAuthenticator, Authenticator>();
            //services.AddScoped<IDialogService, DialogService>();
            services.AddScoped<MainViewModel>();

            services.AddScoped<MainWindow>(s => new MainWindow(s.GetRequiredService<MainViewModel>()));
            return services.BuildServiceProvider();
        }
    }
```

Before the Navigation implementation I was calling the startup ViewModel in the mainViewModel like this 

```
public class MainViewModel : BaseViewModel
    {
        private BaseViewModel _selectedViewModel = new HomeViewModel(new DialogService());

        public MainViewModel()
        {
           
        }
        public BaseViewModel SelectedViewModel
        {
            get { return _selectedViewModel; }
            set { _selectedViewModel = value; }
        }

    }

```

Now the MainViewModel look like this
```
 public class MainViewModel : ViewModelBase
    {
        public INavigator _navigator { get; set; }
        public IAuthenticator Authenticator { get; }
        public IDialogService _dialogService { get; }
        public MainViewModel(INavigator navigator, IAuthenticator authenticator, IDialogService dialogService)
        {
            _dialogService = dialogService;
            _navigator = navigator;
            Authenticator = authenticator;

            _navigator.UpdateCurrentViewModelCommand.Execute(ViewType.Home);
        }
    }
}
```
On my HomeViewModel (on both project) the function is exactly the same 

```
 private void GetGill(object parameter)
        {
            var settings = new OpenFileDialogSettings
            {
                Title = "",
                InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop),
            };
            bool? success =  _dialogService.ShowOpenFileDialog(this, settings);
        }
```
Idk if you need more of the code. If so I can do a repo with the complete project. 
Thanks

**Comment by FantasticFiasco** [comment]
I think the easiest way for me to see the problem is that you create a small repo here on GitHub showcasing the issue. I think that will save a lot of time. Thanks!

**Comment by meilleur102** [comment]
> I think the easiest way for me to see the problem is that you create a small repo here on GitHub showcasing the issue. I think that will save a lot of time. Thanks!

Sorry for the long delay. Ive been put on other thing.
https://github.com/meilleur102/testMvvmDialog
Here's the repo. 
Just run the program and click on the button you will have the error.
Thx

**Comment by FantasticFiasco** [comment]
No problem, I can relate.

I think you forgot to commit a couple of files as the project won't compile. `App` has references to `CncDrillHole.Services`, `CncDrillHole.States.Navigators` and `CncDrillHole.ViewModels` but those folders don't exist in repo on GitHub.

**Comment by meilleur102** [comment]
> No problem, I can relate.
> 
> I think you forgot to commit a couple of files as the project won't compile. `App` has references to `CncDrillHole.Services`, `CncDrillHole.States.Navigators` and `CncDrillHole.ViewModels` but those folders don't exist in repo on GitHub.

wow..was really sleeping yesterday :).
I drag all the file but it seems that git don't take it all..idk why. 
Anyways, I recreate the repo from Visual studio so everything should be there now. 
https://github.com/meilleur102/testMvvmDialog

**Comment by meilleur102** [comment]
Just keep in mind Ive try a lot of thing so maybee the initialisation of the DialogService() is not good. I move so many thing to try to make it work that I'm really lost on this one. 
If you check on App.xaml.cs I add the DialogService in the scoped.
It's since I had the ServiceProvider that I have this problem.

**Comment by meilleur102** [comment]
Ive figure it out....Rookie mistake
I was declaring in the service as a Scoped and not singleton...!

**Comment by FantasticFiasco** [comment]
No problem, glad you found it!
