### ISSUE TITLE
Wiki Custom dialog type locators incorrect

### ISSUE THREAD

**Issue by icameron** [FantasticFiasco/mvvm-dialogs#159]
Please update the Wiki for  Custom dialog type locators as it currently incorrect

**Comment by FantasticFiasco** [comment]
Is it any of the samples that are incorrect or the text?

**Comment by icameron** [comment]
Sorry i should have included more into 

I looks like the DialogService has been updated since the wiki was written as the dialog service params are incorrect in the wiki

dialogService = new DialogService(new MyCustomDialogTypeLocator()); 

should be 

dialogService = new DialogService(null,new MyCustomDialogTypeLocator());

**Comment by FantasticFiasco** [comment]
Thanks! I'll make sure to update it.

**Comment by FantasticFiasco** [comment]
Wiki is updated now, added a working sample for the functionality as well, linked from the wiki. Hopefully I will catch these issues early on given the sample exists and has to compile.

Thanks for writing the issue, it made this project better!
