### ISSUE TITLE
Dialog from constructor

### ISSUE THREAD

**Issue by kodaniel** [FantasticFiasco/mvvm-dialogs#16]
Hi!

How could I create a new dialog window in the constructor?

The problem is, that the viewmodel's constructor runs before the usercontrol is rendered, so your code won't find the view in the registered view's collection.

ViewNotRegisteredException throwed:
"Additional information: View model of type 'Igm.Networking.GridViewModel' is not present as data context on any registered view.Please register the view by setting DialogServiceViews.IsRegistered="True" in your XAML."

Do you know any fancy solution?

br,
Daniel

**Comment by FantasticFiasco** [comment]
> How could I create a new dialog window in the constructor?
Are you trying to open a new dialog from the constructor of a view model? If so, I would advise not to. The constructor should not have any side affects, it should only creating an instance of the class.

If you provide me with a code sample showing of your problem I can show you how you should solve it using this framework.

**Comment by kodaniel** [comment]
> Are you trying to open a new dialog from the constructor of a view model?

Yes.

GridView.xaml:
```xaml
<UserControl x:Class="Igm.Networking.GridView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:md="https://github.com/fantasticfiasco/mvvm-dialogs"
             md:DialogServiceViews.IsRegistered="True">
[...]
</UserControl>
```

GridView.xaml.cs (I'm using prism MEF framework):
```cs
[Export]
public partial class GridView : UserControl
{
    public GridView()
    {
        InitializeComponent();
    }

    [Import]
    public GridViewModel ViewModel
    {
        set { DataContext = value; }
        get { return (GridViewModel)DataContext; }
    }
}
```

GridViewModel.cs:

```cs
[Export, PartCreationPolicy(CreationPolicy.Shared)]
public class GridViewModel : BindableBase
{
    [ImportingConstructor]
    public GridViewModel(IDialogService dialogService)
    {
        if (dialogService == null)
            throw new ArgumentNullException(nameof(dialogService));

        dialogService.ShowMessageBox(this, "Some Initial message on application startup."); // crashes in this line
    }
}
```

**Comment by FantasticFiasco** [comment]
I've created a small sample application ([Issue16_v1.zip](https://github.com/FantasticFiasco/mvvm-dialogs/files/658387/Issue16_v1.zip)) that demonstrates one alternative solution to your problem. The code opening the message box has been moved from the constructor to a new method that is called when the view is loaded.

Please disregard any weird stuff I possibly do with MEF and Prism, it has been a couple of years since I last engaged with those frameworks.

**Comment by kodaniel** [comment]
The only problem with your code is the view's content won't rendered until I not close the dialog window.

But I found a solution, I just simply put the dialog window call into a dispatcher:

```cs
public void ShowInitialMessage()
{
    Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.ContextIdle, new Action(() =>
    {
        dialogService.ShowMessageBox(this, "Some Initial message on application startup.");
    }));
}
```

If you haven't got any better suggestion or solution, you can close the issue. Thank you for your help!

**Comment by FantasticFiasco** [comment]
Sorry for not noticing it myself. Allowing the UI thread to continue draw the UI, and postponing opening the dialog to after the UI thread is done, seems to be a very good solution.

If you find this project useful, please don't hesitate to give it a star. If you encounter any problems with this framework, please ask me again.
