### ISSUE TITLE
Avalonia Support

### ISSUE THREAD

**Issue by mysteryx93** [FantasticFiasco/mvvm-dialogs#172]
With Avalonia UI, this is how they recommend openign a dialog with ReactiveUI.
https://docs.avaloniaui.net/tutorials/music-store-app/opening-a-dialog

Plenty of boiler-plate and code in the view.

The MvvmDialogs method is way prettier.

What would it take to support Avalonia with MvvmDialogs?

Because of extra dependencies, it would need to be an extra assembly.

**Comment by FantasticFiasco** [comment]
I really don't know. It seems like Avalonia UI is using WPF, but they also target macOS and Linux. Didn't know this was possible.

It's really hard at this point to say whether it would be easy or not. I assume you've tried to add MVVM Dialogs to an Avalonia project and verified that it doesn't work?

**Comment by mysteryx93** [comment]
It's "like" WPF but uses different namespaces. There's no reference to WPF classes.

Should be very easy to port. So far, porting my code from WPF to Avalonia UI is merely changing namespaces and simplifying the code for a better API. Converting the other way from Avalonia UI to WPF, however, would be a bit more frustrating.

**Comment by FantasticFiasco** [comment]
I currently don't have any bandwidth for analyzing and implementing this, but let's leave this issue open and see whether it get's and traction.

If you attempt to integrate this library into Avalonia UI, please let me know of the outcome.

**Comment by mysteryx93** [comment]
I probably can do it, as a separate assembly, and would appreciate a few pointers as to what would need to be done.

Btw does the base library have dependency on WPF? I guess so... that can be an issue in and of itself. That would be the biggest obstacle.

You would need to split the library into MvvmDialogs.Core with no UI dependency, and then MvvmDialogs.WPF, MvvmDialogs.UWP, MvvmDialogs.WinUI3, MvvmDialogs.Avalonia for platform-specific code

If you can split WPF code away from the Core, then I can copy the WPF code and tweak it.

Otherwise we end up with a library with DLL references to lots of unused libraries; including libraries that are not cross-platform compatible.

**Comment by FantasticFiasco** [comment]
This library definitely has dependencies on WPF, and I'm starting to question whether this is a direction this library should take. It's a lot of work, and the value is undetermined.

This probably wouldn't getting merged, the required changes are too many.

**Comment by FantasticFiasco** [comment]
Looking back at the previous two months and the time I've been able to dedicate to this endeavour, I've come to the conclusion that the changes aren't feasible for the project. I'm really sorry about it, but don't see my priorities shifting in a direction where I will be able to dedicate more time on this issue. Your best bet is to copy or fork the repository, and publish your own NuGet package under a different name.

Thank you for your engagements in this project and best of luck in the future.
