### ISSUE TITLE
There must be View(Dialog) and ViewModel in the same assembly.

### ISSUE THREAD

**Issue by hhko** [FantasticFiasco/mvvm-dialogs#19]
private static Assembly GetAssemblyFromType(Type type)
        {
#if NETFX_CORE
            // GetTypeInfo is supported on UWP
            return type.GetTypeInfo().Assembly;
#else
            // Assembly is supported on all .NET versions
            **return type.Assembly;**
#endif
        }

Do you have any plans to support the different assemblies for View(Dialog) and ViewModel?

**Comment by FantasticFiasco** [comment]
Not in `NamingConventionDialogTypeLocator`, but `DialogService` is built to support whatever implementation of `IDialogTypeLocator` you decide is correct for your project, thus you can easily implement a custom locator yourself and pass it to `DialogService` when you create the instance.

**Comment by hhko** [comment]
I didn't know IDialogTypeLocator interface.
Thank you for your consideration.

**Comment by hhko** [comment]
Do you have a plan to add the demo and wiki about how to implement IDalogTypeLocator interface?

**Comment by FantasticFiasco** [comment]
Not until now. Can you give me some bulletpoints of what you would like that wiki to contain?

**Comment by hhko** [comment]
The IDalogTypeLocator interface doesn't mention any information in Wiki.

**Comment by FantasticFiasco** [comment]
You are correct, there is information lacking both when it comes to dialog type locators and dialog factories, concepts that are possible to inject custom implementations of.

Thank you for bringing this to my attention, I'll see if I can do anything about that.

**Comment by FantasticFiasco** [comment]
I'm reopening this issue, because after updating the wiki I would like you the be the judge whether the information there is informative.

Would that be ok for you?

**Comment by FantasticFiasco** [comment]
I've added a wiki page about [custom dialog locators](https://github.com/FantasticFiasco/mvvm-dialogs/wiki/Custom-dialog-type-locators), and how you should use them.

I would be ever so grateful if you where able to read though it and give me feedback on whether the text is informative, whether I got any typos in there, or if something is missing.

Thanks!

**Comment by hhko** [comment]
I'm really sorry not to notify it.
I've already read your fantastic and kind article about custom dialog locators.

Mvvm-dialogs is one of my favorite libraries.
I hope sustaining mvvm-dialogs's growth!

Thank you^^;;;
