### ISSUE TITLE
Avalonia support

### ISSUE THREAD

**Issue by timunie** [FantasticFiasco/mvvm-dialogs#205]
**Is your feature request related to a problem? Please describe.**
I use Avalonia which also supports MVVM and XAML. As for all MVVM Framworks, handling dialogs can be... difficult. What do you think about extending this lib for Avalonia? (http://avaloniaui.net)

**Describe the solution you'd like**
Add Avalonia support

**Describe alternatives you've considered**
keep it as it is 

**Additional context**
If you find this useful, I may have a look if I manage to port it and make a PR.

**Comment by FantasticFiasco** [comment]
Hi @timunie!

It's a topic that has been discussed in #177 and #172. We started looking into supporting Avalonia,  but unfortunately I found that it required more work than I was able to muster.

I think you should contact [mysteryx93](https://github.com/mysteryx93). He forked this repository and got it to work on Avalonia.

**Comment by timunie** [comment]
Ah sorry I have overseen this. I fully understand your concerns and the effort it would take.. 👍 

Thank you for the fast and detailed feedback. 👍 🌹

**Comment by FantasticFiasco** [comment]
No problems at all, I hope you will be able to use the fork.

**Comment by mysteryx93** [comment]
[UPDATE: First official release for WPF & Avalonia!](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs)

I'm quite proud of how it came out.

**Comment by FantasticFiasco** [comment]
Nice, good job! I'll direct all questions regarding Avalonia to this repo.

**Comment by timunie** [comment]
> [UPDATE: First official release for WPF & Avalonia!](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs)
> 
> I'm quite proud of how it came out.

You really can be 👍 . Thank you very much for the effort ❤️ .

I'll share the link to your repo on the Avalonia telegram channel.
