### ISSUE TITLE
Issue with partial WPF hosts

### ISSUE THREAD

**Issue by BMurri** [FantasticFiasco/mvvm-dialogs#21]
I'm working on a project where there is no top-level WPF Window, so my modal dialogs need the ability to use WindowInteropHelper to set their parentage (I do have the IntPtr of the HWND to use). I'm writting a plugin in their system. They host a smattering of WPF framework elements scattered around a Win32 window (their primary codebase is native C++, and they use a combination of WPF and WinForms to create various elements of their UI).

**Comment by BMurri** [comment]
I've got a couple ideas on how to proceed, but I first want to know your thoughts on if this is something you would consider in your project.

**Comment by FantasticFiasco** [comment]
Hi BMurri and welcome to the project!

I once worked on a desktop application that was a combination of WPF and WinForms, and it was horrific. Now you tell me that your application also involve Win32 and C++? I feel for you...

I will state right up front that you are the first to ask for non-WPF support, which leads me to believe that the feature won't get any traction. I'm also afraid that going native will disrupt the support for UWP, or is IntPtr, HWND and WindowInteropHelper also present there?

If you find any other frameworks supporting your requirements, you should go for those. If you find MVVM Dialogs to be the closest match to a solution, you should fork this repo and do the necessary changes. I cannot however give you my word that those changes will be pulled back to this repo, that would depend on the nature of the implementation.

In any case, I wish you the best of luck with your application, and hope to hear from you again.
