### ISSUE TITLE
Show dialog in App.xaml.cs

### ISSUE THREAD

**Issue by mikehachen** [FantasticFiasco/mvvm-dialogs#22]
Hi there

First of all thank you for your work! It helped me a lot and is really a time saver 👍 

One (small) question:
If I want to show a MessageBox I have to provide a ownerViewModel. For that I add `md:DialogServiceViews.IsRegistered="True"` wherever I need dialogs. Now I need to do some basic start up work (check connection, setting connection up etc.). I do this in the `private void App_OnStartup(object sender, StartupEventArgs e)` Event which is located in the App.xaml.cs file. I can't add the `md:DialogServiceViews.IsRegistered="True"` in the App.xaml file because the attached property can only be applied to types that are derived from "DependencyObject". So how can I show dialogs with your framework within App.xaml.cs?

Thank you four your help!
Mike

**Comment by FantasticFiasco** [comment]
Hi Michael!

I would argue that you probably should't use MVVM Dialogs in `App.xaml.cs` when you're opening your message box, you should open the dialog using `MessageBox.Show`.

> Why?

Well, one of the benefits of using MVVM Dialogs is that you create an abstraction between your view models and opening a message box, and that abstraction can be mocked in tests.

I bet you don't have tests that run on `App.xaml.cs`, thus there is no benefit from using MVVM Dialogs to open a message box in that file.

Am I making any sense?
