### ISSUE TITLE
Cascade windows opening & MVVMLight requirement

### ISSUE THREAD

**Issue by Niko0pl** [FantasticFiasco/mvvm-dialogs#23]
Hello @FantasticFiasco,
Can I use your Framework for opening Windows one from another? Like: `InitialWindow -> MainWindow -> SomeDialog`. If so I would be grateful for some tip how to do that. 
I would also like to ask about registering in `SimpleIoc` I do not use any framework for MVVM. Is the MVVMLight required for your framework to work?

**Comment by FantasticFiasco** [comment]
Hi Niko0pl, welcome to MVVM Diaogs!

> Can I use your Framework for opening Windows one from another? Like: `InitialWindow -> MainWindow -> SomeDialog. `

Yes, there should be nothing special about opening a second window compared to opening the first window. Please take a look at the [demos](https://github.com/FantasticFiasco/mvvm-dialogs/tree/master/src/NET/Demos), there you will find examples on how to open windows.

> I would also like to ask about registering in `SimpleIoc` I do not use any framework for MVVM. Is the MVVMLight required for your framework to work?

No, MVVM Dialogs does not require MVVMLight or any other MVVM framework, it can stand on its own.

**Comment by Niko0pl** [comment]
> Yes
So should I pass IDialogService to the constructor of VM of every window that is supposed to open another, and register view in xaml?
> No
So how can I replace `SimpleIoc.Default.Register<IDialogService>(() => new DialogService());` in App.xaml.cs then?

**Comment by FantasticFiasco** [comment]
> So should I pass IDialogService to the constructor of VM of every window that is supposed to open another, and register view in xaml?

That depends on whether you use dependency injection is you application or not. Usually when you use dependency injection you pass the dependencies to a class in the constructor. But if you don't use dependency injection you can either create a Singleton instance of `IDialogService`, or you can even create new instances of `DialogService` in every class you wish to open a dialog from. `DialogService` is implemented to be stateless, thus there is only a minor performance penalty when creating more than one instance of the class.

> So how can I replace SimpleIoc.Default.Register<IDialogService>(() => new DialogService()); in App.xaml.cs then?

From this question I assume you don't use dependency injection. Referring to my answers above, either create a Singleton instance of `DialogService`, or create the class in all view models opening dialogs.

**Comment by Niko0pl** [comment]
@FantasticFiasco thank you for your help and sorry for the basic question (this is my first independent project in MVVM). I've decided to do a static Singleton.
Unfortunately, all the time I got an error in both explicit and implicit show, in the arguments of `Show(this, viewmodel)` method: `Error	CS1503	Argument 1: cannot convert from 'ViewModels.MainWindowViewModel' to 'System.ComponentModel.INotifyPropertyChanged'` and exactly the same for the second argument. Do you know what it can be?

**Comment by FantasticFiasco** [comment]
I was just about to create a basic sample for you, but you solved it yourself, so 🍰 for you!

Just let me know if you experience anything out of the ordinary, and I'll try to help you.

**Comment by Niko0pl** [comment]
Thats really kind of you.
Regarding my previous post, I had to add `INotifyPropertyChanged` and rebuild to remove that errors.

**Comment by FantasticFiasco** [comment]
MVVM Dialogs is opinionated when it comes to view models, but for a good reason. The change detection mechanism in WPF is most performant when the view models implement `INotifyPropertyChanged`.

One could argue that the error message displayed could be better, but then again I don't often get questions regarding this particular error.
