### ISSUE TITLE
Unable to use IDialogService in constructor

### ISSUE THREAD

**Issue by AlanBontoft-Druck** [FantasticFiasco/mvvm-dialogs#239]
Firstly, I'd like to say great library!

I'm not sure if it's the way I'm using it, but if I try to use the service in the constructor of a View Model that receives the service as a parameter, I get the error "MvvmDialogs.ViewNotRegisteredException".  It informs me to add the decoration DialogServiceViews.IsRegistered="True" to the XAML, even though this has already been done.

This can be reproduced by adding the line:

 'dialogService.ShowMessageBox(this, "Test");'

to the end of the MainWindowViewModel constructor in the https://github.com/FantasticFiasco/mvvm-dialogs-integrated-into-windows-community-toolkit example.

Using the service after the constructor has completed works as expected.

I would be interested to hear if there is a work-around for this?

Thanks

**Comment by AlanBontoft-Druck** [comment]
Mattias

Thanks for the swift reply.  I'll have a look at your recommendations above.

**Comment by FantasticFiasco** [comment]
Closed due to inactivity, please let me know if you want this opened again
