### ISSUE TITLE
InvalidOperationException when multiple UI threads are used

### ISSUE THREAD

**Issue by HeedfulCrayon** [FantasticFiasco/mvvm-dialogs#263]
**Describe the bug**

When using multiple STA threads in an application (Main window that launches a child window in a new STA thread), the DialogService registers the views from multiple threads correctly.  When accessing the views to find the owner, the application will crash with an InvalidOperationException stating "The calling thread cannot access this object because a different thread owns it"

**To Reproduce**

1. You need a thread safe ServiceProvider that can give you access to the DialogService you registered across multiple threads (we are using the CommunityToolkit IoC).
2. Create a Main window that registers a view with the DialogServiceViews.
3. Create a new STA thread that launches a new window that also registers a view with the DialogServiceViews.
4. Try to show the second view that was registered using the DialogService.
5. Observe the crash

**Expected behavior**

The views should be registered in a threadsafe collection, and have checks so that the views that the DialogService is trying to find the owner for are only related to the current thread calling it.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**

I have implemented a fix using a ConcurrentDictionary collection.  I will reference this issue in that PR, but I would love any feedback you may have on it.

**Comment by HeedfulCrayon** [comment]
Actually, the simplest course of action would to make the `IView` interface and the `ViewWrapper` class and properties public.  That way someone with special needs could implement their own DialogServiceViews class and DialogService class

**Comment by FantasticFiasco** [comment]
@HeedfulCrayon I think that would be better than adding changes to the public API. Do you have any code snippets we could add as tests making sure that this functionality doesn't regress with new versions?

**Comment by FantasticFiasco** [comment]
I'd happily collaborate with you on it. Tell me what you want to do and I'll do the other parts. We can work on a branch in your fork?

**Comment by HeedfulCrayon** [comment]
> @HeedfulCrayon I think that would be better than adding changes to the public API. Do you have any code snippets we could add as tests making sure that this functionality doesn't regress with new versions?

I did update the tests in my thread safe version, and all the tests seem to be passing.  As for creating a multithreaded test to verify that it is working in a multithreaded scenario, I couldn't figure out how to do that.  I will hopefully get a branch on my fork up in an hour or two

**Comment by FantasticFiasco** [comment]
Don't haste, I won't be able to make any contribution for a day or so.

**Comment by HeedfulCrayon** [comment]
Sorry, relatively new to open source collaboration.  I forgot to remove some extra stuff I was using for debugging.  My fork should demonstrate the fix.  It also shouldn't break any existing unit tests

**Comment by FantasticFiasco** [comment]
np! I'll look into the changes. Do you have a small snippet or sample application that would demonstrate your setup with multiple STA threads? I'll look into whether we will test this using unit tests or automated integration tests.

**Comment by HeedfulCrayon** [comment]
I can't really provide a snippet or sample, but the idea is this.  Imagine a traditional MVVM application, and in the ViewModel you create a new thread, set it's apartment state to STA and that thread launches a new window.  Now both windows have separate UI threads.  The reason behind it is there is a Control Center that launches child windows.  You can launch multiple child windows that should all have their own UI threads.

**Comment by HeedfulCrayon** [comment]
I have an idea for testing the threading aspect.  I will have it up soon

**Comment by FantasticFiasco** [comment]
I like your test! I'm looking into building a sample showcasing the support for different STA threads.

**Comment by FantasticFiasco** [comment]
Could you please open up a new pull request from the `bug/FixInvalidOperationExceptionWithMultiThreading` branch, and check the option to allow me to push changes to this branch? Thanks!

**Comment by HeedfulCrayon** [comment]
Looks like there is one test failure.  I will see if I can solve that issue

**Comment by HeedfulCrayon** [comment]
Got it fixed.  I needed to use the View's HashCode instead of the View Id since the ViewWrapper generates a new Id every time
