### ISSUE TITLE
Solution build errors using Visual Studio 2017

### ISSUE THREAD

**Issue by kdotdk** [FantasticFiasco/mvvm-dialogs#28]
Hi
I am unable to build and run e.g. Demo.MessageBox.
I did:
1. Downloaded master of mvvm-dialogs as zip.
2. Opened and rebuilded the solution MvvmDialogs.sln in Visdual Studio.

Result 147 errors like:
- Error CS0246	The type or namespace name 'GalaSoft' could not be found (are you missing a using directive or an assembly reference?)	Demo.FolderBrowserDialog	\mvvm-dialogs-master\src\NET\Demos\Demo.FolderBrowserDialog\App.xaml.cs	2
- Error CS0246	The type or namespace name 'ViewModelBase' could not be found (are you missing a using directive or an assembly reference?)	Demo.FolderBrowserDialog	C:\TFS\KNRTests\mvvm-dialogs-master\src\NET\Demos\Demo.FolderBrowserDialog\MainWindowViewModel.cs	11	Active

It look like the hintpath to mvvmlight and others in csproj files is wrong.
Hints about that is missing is appreciated. Any global setup perhaps.

I initially tried follow the instuction in README.md file to add mvvm-dialogs to an project created with MVVMLigh WPF 451 project template in visual studio  - but the application crached when started - this is why I am trying to run the Demo.MessageBox.

**Comment by FantasticFiasco** [comment]
Hi!

I will look into the hint paths, you could have found something there.

**Comment by FantasticFiasco** [comment]
You where absolutely right, the hint paths where all wrong. Thanks for the heads up! Pull the latest changes, and you should be able to build the solution.
