### ISSUE TITLE
DialogResult can be set only after Window is created and shown as dialog.

### ISSUE THREAD

**Issue by caibf** [FantasticFiasco/mvvm-dialogs#36]
### Step 1: Describe your environment

* Operating system? Windows 7 x64 +Visual Studio 2015 Update 3
   
#### Steps to reproduce:

1. My business logic is opening a same dialog which used to connect to server and wating the result return.
2.The connection result is true&false that return by server for closing the dialog.
3.The dialog is opening and closing normally first time when the dialog result is set to 【true】. And then, the dialog is opening and closing normally second time when the dialog result is set to 【false】. Thus, when I opening the same dialog third time and closing with the dialog result is set to 【true】. The exception is happen, detailed infomation I copy from VS debugger.
 
#### Observed results

* What happened? This could be a description, log output, etc.

I use log4.net to write down exception is here: 
     在 System.Windows.Window.set_DialogResult(Nullable`1 value)
   在 MvvmDialogs.DialogService.<>c__DisplayClass20_0.<RegisterDialogResult>b__0(Object sender, PropertyChangedEventArgs e)
   在 System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   在 GalaSoft.MvvmLight.ObservableObject.RaisePropertyChanged(String propertyName) 位置 D:\GalaSoft\mydotnet\MVVMLight\source\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\ObservableObject.cs:行号 200
   在 SDPCClient.Dialog.ViewModels.ProgressDialogViewModel.set_DialogResult(Nullable`1 value) 位置 F:\Projects\SDPC\SDPCClient\SDPCClient\Dialog\ViewModels\ProgressDialogViewModel.cs:行号 148
   在 SDPCClient.Dialog.ViewModels.ProgressDialogViewModel.<>c__DisplayClass13_0.<TerminateDialog>b__0() 位置 F:\Projects\SDPC\SDPCClient\SDPCClient\Dialog\ViewModels\ProgressDialogViewModel.cs:行号 228
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Window.ShowHelper(Object booleanBox)
   在 System.Windows.Window.ShowDialog()

#### Expected results

* What did you expect to happen?
The same dialog(ony one instance there) that I can use the interface of IDialogService.ShowDialog() to open and close would normally execuate.

**Comment by FantasticFiasco** [comment]
Hi caibf!

Would it be possible for you to build a small sample application that verifies the issue?

Thanks!

**Comment by caibf** [comment]
Hi, thans for your reply!

I do NOT sure the issue is caused by whether the mvvm-dialogs package or my business code. I have checked my code many times carefully but couldn't find any problem. Seaching the problem from Google I found some one meet the same problem with me.

**Comment by FantasticFiasco** [comment]
I'll see if I can reproduce the issue based on your provided stack trace, but cannot guarantee anything

**Comment by FantasticFiasco** [comment]
Closed due to inactivity.
