### ISSUE TITLE
Proposal: Switch CreateFolderBrowserDialog to use the COM IFileDialog API

### ISSUE THREAD

**Issue by Jehoel** [FantasticFiasco/mvvm-dialogs#37]
I noticed that MvvmDialogs 5.1.0.0 takes a dependency on  `System.Windows.Forms.dll` because it uses the WinForms dialogs inside `DefaultFrameworkDialogFactory` for `CreateFolderBrowserDialog`.

The WinForms folder browser is the older, single tree-view based dialog.

Windows also has a COM Shell API interface for common file dialogs - which is where the new, explorer-style folder browse dialog comes from. WinForms does not use this dialog, but the Windows API Code-pack library does. 

I ripped-out the dialog-specific stuff and repackaged it into its own assembly (and the code-files could just be compiled into a single assembly anyway) which is available at https://github.com/Jehoel/ShellFileDialogs

I propose including this code into this project and using that for `CreateFolderBrowserDialog` (and the File Open and File Save dialogs, though there's less benefit there, but it would mean losing the dependency on `System.Windows.Forms.dll`.

**Comment by FantasticFiasco** [comment]
Hi and welcome!

Yes it is true that the library has a dependency towards `System.Windows.Forms`, I think it is one of those things that just happened to be. One can always opt in for custom dialogs by implementing `IFrameworkDialogFactory`, but as you say, the default one uses WinForms.

I'll look at the code and the COM Shell APIs. Lets hope that there is a chance of migrating without introducing breaking changes, in other case, we can always provide a framework dialog factory that uses the COM API in the [MVVM Contrib repo](https://github.com/FantasticFiasco/mvvm-dialogs-contrib).

**Comment by FantasticFiasco** [comment]
I think this feature would be wonderful for [MVVM Dialogs Contrib](https://github.com/FantasticFiasco/mvvm-dialogs-contrib).

**Comment by Jehoel** [comment]
I've performed the integration and created a PR: https://github.com/FantasticFiasco/mvvm-dialogs-contrib/pull/2

**Comment by Jehoel** [comment]
Thank you :)

**Comment by FantasticFiasco** [comment]
I'm the one who should thank you, you did all the work :-)

I will release an official version on the Contrib NuGet package later this week.
