### ISSUE TITLE
ViewNotRegisteredException

### ISSUE THREAD

**Issue by Streissi** [FantasticFiasco/mvvm-dialogs#41]
#### Environment:
Win 10, 64Bit / Win 7, 64Bit
Visual Studio 2017 15.8.3
MvvmDialogs 5.1.0
Prism 6.3.0

#### Problem
Hi, i want to show a dialog direct after the application starts. I use Prism to handle the Mvvm Pattern.  To start the dialog i added your DialogService to the prism container. I start the dialog directly after the main window was shown via the bootstrapper:

```
            App.Current.MainWindow.Show();
            var dialogService = Container.Resolve<IDialogService>();
            if(dialogService != null)
            {
                var mainViewModel = ((Window)Shell).DataContext as MainWindowViewModel;
                var dialogModel = Container.Resolve<InfoViewModel>();
                dialogService.ShowDialog(mainViewModel, dialogModel);
            }
```
On my Win10 machine works all fine, but if i copy the hole source code to a win7 machine and i start the startup project it stops with an MvvmDialogs.ViewNotRegisteredException exception at the `dialogService.ShowDialog(...)` line

The view header is:

```
<Window x:Class="ModelCalculation.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:prism="http://prismlibrary.com/"
        xmlns:md="https://github.com/fantasticfiasco/mvvm-dialogs"
        prism:ViewModelLocator.AutoWireViewModel="True"
        md:DialogServiceViews.IsRegistered="True"
        mc:Ignorable="d"
        WindowState="Maximized"
        WindowStartupLocation="CenterScreen"
        Title="MainWindow" Height="800" Width="1024">
```
The viewmodel is definitely the datacontext of the window.

**Comment by FantasticFiasco** [comment]
Hi and welcome to the project!

1. Which version of Windows 7 are you running?
2. Which version of .NET Framework are you running on Windows 7?
3. Would you be able to provide me with a small sample application which demonstrate this issue on Windows 7?

**Comment by Streissi** [comment]
Hi and thank you for your fast reply.

- Winows 7 Pro - 64Bit  - Service Pack 1
- .Net Framework 4.5

I will try to create a sample application

**Comment by Streissi** [comment]
Hi
here is a test repo: https://github.com/Streissi/MvvmDialogIssue41.git
While creating the test app i figured out that the Property `WindowState="Maximized"` cause the issue.

**Comment by FantasticFiasco** [comment]
Interesting! I will use your repo and see if I can reproduce the issue on my side. I wonder why maximizing the window would cause the issue... Don't expect any updates from me today, I first have to get hold on a Window 7 instance.

**Comment by Streissi** [comment]
i forked you repo to debug why the maximized state couse the issue.
At the time i opened the dialog, the main window was not loaded.
so i attached to the loaded event of the mainwindow and it works no also on windows 7. I think it was not a specific operating system problem, more a time problem.
My win 10 machine is more powerfull than the win 7 virtual machine.

**Comment by FantasticFiasco** [comment]
Well, this was probably the best issue to date, you solved everything yourself :D

If you encounter any other problems, please let me know.

Happy coding!
