### ISSUE TITLE
Add support for ValidateNames dialog property

### ISSUE THREAD

**Issue by Kimmerest** [FantasticFiasco/mvvm-dialogs#91]
It appears there isn't currently support for the Windows dialog property ValidateNames.  It would be really fantastic if that could be added.

**Comment by FantasticFiasco** [comment]
Hi!

Would you be able to provide a code sample showing the usage of `ValidateNames`? If it is something I've missed I'd happily add it and make sure that tests are validating its behavior as well.

**Comment by FantasticFiasco** [comment]
Just to be clear, how you'd wish to configure `ValidateNames` using MVVM Dialogs.

**Comment by FantasticFiasco** [comment]
I'm about to complete the implementation. Would you be willing to try the new functionality before I officially release it?

**Comment by FantasticFiasco** [comment]
The property `ValidateNames` should now exist on the latest released NuGet.

Thank you for raising this issue.
